const Plan = require('../models/Plan');
const automatedPlanningService = require('../services/automatedPlanningService');
const logger = require('../utils/logger');

/**
 * Planning Controller
 * Views and manages AUTO-GENERATED business plans
 * Plans are created automatically by the system, not by users
 */

/**
 * Get all plans for current user (auto-generated by system)
 * @route GET /api/planning
 */
exports.getUserPlans = async (req, res) => {
  try {
    const userId = req.user._id;
    const {
      status,
      planType,
      limit = 20,
      page = 1,
    } = req.query;

    const query = { userId };

    if (status) query.status = status;
    if (planType) query.planType = planType;

    const skip = (parseInt(page) - 1) * parseInt(limit);

    const [plans, total] = await Promise.all([
      Plan.find(query)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(parseInt(limit))
        .populate('relatedForecastId', 'forecastType forecastPeriod forecast')
        .lean(),
      Plan.countDocuments(query),
    ]);

    res.json({
      success: true,
      message: 'These plans were automatically generated by the system based on your data',
      data: {
        plans,
        pagination: {
          total,
          page: parseInt(page),
          limit: parseInt(limit),
          pages: Math.ceil(total / parseInt(limit)),
        },
      },
    });
  } catch (error) {
    logger.error(`Get user plans error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching plans',
      error: error.message,
    });
  }
};

/**
 * Get active plans (currently being executed)
 * @route GET /api/planning/active
 */
exports.getActivePlans = async (req, res) => {
  try {
    const userId = req.user._id;

    const plans = await Plan.getActivePlans(userId);

    res.json({
      success: true,
      message: 'Active plans automatically generated by the system',
      data: plans,
    });
  } catch (error) {
    logger.error(`Get active plans error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching active plans',
      error: error.message,
    });
  }
};

/**
 * Get specific plan by ID
 * @route GET /api/planning/:id
 */
exports.getPlanById = async (req, res) => {
  try {
    const userId = req.user._id;
    const { id } = req.params;

    const plan = await Plan.findOne({ _id: id, userId })
      .populate('relatedForecastId')
      .populate('actualResults.recordedBy', 'name email');

    if (!plan) {
      return res.status(404).json({
        success: false,
        message: 'Plan not found',
      });
    }

    res.json({
      success: true,
      data: plan,
    });
  } catch (error) {
    logger.error(`Get plan by ID error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching plan',
      error: error.message,
    });
  }
};

/**
 * Update action item status (user can check off actions)
 * @route PATCH /api/planning/:id/actions/:actionId
 */
exports.updateActionItem = async (req, res) => {
  try {
    const userId = req.user._id;
    const { id, actionId } = req.params;
    const updates = req.body;

    const plan = await Plan.findOne({ _id: id, userId });

    if (!plan) {
      return res.status(404).json({
        success: false,
        message: 'Plan not found',
      });
    }

    await plan.updateActionItem(actionId, updates);

    logger.info(`Action item ${actionId} updated in plan ${id} by user ${userId}`);

    res.json({
      success: true,
      message: 'Action item updated successfully',
      data: plan,
    });
  } catch (error) {
    logger.error(`Update action item error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error updating action item',
      error: error.message,
    });
  }
};

/**
 * Update milestone progress
 * @route PATCH /api/planning/:id/milestones/:milestoneId
 */
exports.updateMilestone = async (req, res) => {
  try {
    const userId = req.user._id;
    const { id, milestoneId } = req.params;
    const { actualValue, status, notes } = req.body;

    const plan = await Plan.findOne({ _id: id, userId });

    if (!plan) {
      return res.status(404).json({
        success: false,
        message: 'Plan not found',
      });
    }

    const milestone = plan.milestones.id(milestoneId);

    if (!milestone) {
      return res.status(404).json({
        success: false,
        message: 'Milestone not found',
      });
    }

    if (actualValue !== undefined) milestone.actualValue = actualValue;
    if (status) milestone.status = status;
    if (notes !== undefined) milestone.notes = notes;

    await plan.save();

    logger.info(`Milestone ${milestoneId} updated in plan ${id} by user ${userId}`);

    res.json({
      success: true,
      message: 'Milestone updated successfully',
      data: plan,
    });
  } catch (error) {
    logger.error(`Update milestone error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error updating milestone',
      error: error.message,
    });
  }
};

/**
 * Update plan status (accept, reject, pause)
 * @route PATCH /api/planning/:id/status
 */
exports.updatePlanStatus = async (req, res) => {
  try {
    const userId = req.user._id;
    const { id } = req.params;
    const { status, notes } = req.body;

    const validStatuses = ['active', 'completed', 'cancelled', 'archived'];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        message: `Invalid status. Must be one of: ${validStatuses.join(', ')}`,
      });
    }

    const plan = await Plan.findOne({ _id: id, userId });

    if (!plan) {
      return res.status(404).json({
        success: false,
        message: 'Plan not found',
      });
    }

    plan.status = status;
    if (notes) plan.notes = notes;

    await plan.save();

    logger.info(`Plan ${id} status updated to ${status} by user ${userId}`);

    res.json({
      success: true,
      message: 'Plan status updated successfully',
      data: plan,
    });
  } catch (error) {
    logger.error(`Update plan status error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error updating plan status',
      error: error.message,
    });
  }
};

/**
 * Get plan statistics
 * @route GET /api/planning/stats
 */
exports.getPlanStats = async (req, res) => {
  try {
    const userId = req.user._id;
    const { startDate, endDate } = req.query;

    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;

    const stats = await Plan.getPlanStats(userId, start, end);

    res.json({
      success: true,
      data: stats,
    });
  } catch (error) {
    logger.error(`Get plan stats error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching plan statistics',
      error: error.message,
    });
  }
};

/**
 * Trigger manual analysis for current user
 * Forces system to analyze performance and generate plans if needed
 * @route POST /api/planning/analyze
 */
exports.triggerAnalysis = async (req, res) => {
  try {
    const userId = req.user._id;

    await automatedPlanningService.triggerManualAnalysis(userId);

    logger.info(`Manual planning analysis triggered for user ${userId}`);

    res.json({
      success: true,
      message: 'Analysis triggered. The system will generate plans if needed based on your current performance.',
    });
  } catch (error) {
    logger.error(`Trigger analysis error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error triggering analysis',
      error: error.message,
    });
  }
};

/**
 * Get plan insights - Why was this plan created?
 * @route GET /api/planning/:id/insights
 */
exports.getPlanInsights = async (req, res) => {
  try {
    const userId = req.user._id;
    const { id } = req.params;

    const plan = await Plan.findOne({ _id: id, userId });

    if (!plan) {
      return res.status(404).json({
        success: false,
        message: 'Plan not found',
      });
    }

    // Extract insights about why this plan was created
    const insights = {
      planType: plan.planType,
      trigger: plan.description || 'Automatic system analysis',
      baseline: plan.baseline,
      goals: plan.goals,
      strategy: {
        summary: plan.strategy.summary,
        keyInsights: plan.strategy.keyInsights,
        risks: plan.strategy.risks,
        opportunities: plan.strategy.opportunities,
      },
      relatedForecast: plan.relatedForecastId ? 'This plan was created based on a forecast prediction' : null,
    };

    res.json({
      success: true,
      data: insights,
    });
  } catch (error) {
    logger.error(`Get plan insights error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching plan insights',
      error: error.message,
    });
  }
};

/**
 * Admin: Trigger analysis for all users
 * @route POST /api/planning/admin/analyze-all
 */
exports.triggerAnalysisAll = async (req, res) => {
  try {
    // This would be called by admin/cron
    logger.info('Manual trigger for all users analysis');

    const User = require('../models/User');
    const activeUsers = await User.find({ isActive: true });

    let analyzed = 0;
    for (const user of activeUsers) {
      try {
        await automatedPlanningService.triggerManualAnalysis(user._id);
        analyzed++;
      } catch (error) {
        logger.error(`Error analyzing user ${user.email}: ${error.message}`);
      }
    }

    res.json({
      success: true,
      message: `Analysis triggered for ${analyzed} users`,
      data: {
        totalUsers: activeUsers.length,
        analyzed,
      },
    });
  } catch (error) {
    logger.error(`Trigger analysis all error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error triggering analysis for all users',
      error: error.message,
    });
  }
};
