const mongoose = require('mongoose');

/**
 * Alert Schema
 * Stores operational intelligence alerts (EIO - Inteligencia Operativa)
 * Automatically generated by the system when issues are detected
 */
const alertSchema = new mongoose.Schema({
  // User who owns this alert
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  userName: String,
  userEmail: String,

  // Alert classification
  type: {
    type: String,
    enum: ['warning', 'critical', 'info', 'opportunity'],
    required: true,
    index: true,
  },
  category: {
    type: String,
    enum: ['roas', 'stock', 'customer_service', 'revenue', 'campaign', 'operations', 'forecast', 'general'],
    required: true,
    index: true,
  },

  // Alert content
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },

  severity: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    required: true,
    index: true,
  },

  // Status workflow: pending → applied/ignored/in_review → resolved
  status: {
    type: String,
    enum: ['pending', 'applied', 'ignored', 'in_review', 'resolved'],
    default: 'pending',
    index: true,
  },

  // Metric that triggered the alert
  metric: {
    name: String,
    currentValue: Number,
    previousValue: Number,
    threshold: Number,
    changePercentage: Number,
    unit: String,
    trend: String, // 'up', 'down', 'stable'
  },

  // AI-generated recommended actions
  recommendedActions: [{
    _id: { type: mongoose.Schema.Types.ObjectId, auto: true },
    title: String,
    description: String,
    actionType: {
      type: String,
      enum: ['increase_budget', 'decrease_budget', 'pause_campaign', 'resume_campaign', 'restock', 'respond_tickets', 'adjust_pricing', 'optimize_campaign', 'custom'],
    },
    parameters: mongoose.Schema.Types.Mixed, // Action-specific data
    estimatedImpact: String,
    applied: { type: Boolean, default: false },
    appliedAt: Date,
    appliedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    result: String, // Result after applying action
  }],

  // Auto-apply capability
  canAutoApply: {
    type: Boolean,
    default: false,
  },
  autoApplied: {
    type: Boolean,
    default: false,
  },
  autoAppliedAt: Date,

  // Related entities
  relatedPlanId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Plan',
  },
  relatedCampaignId: String,
  relatedForecastId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ForecastHistory',
  },
  relatedGuardrailId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CampaignGuardrail',
  },

  // Time tracking
  detectedAt: {
    type: Date,
    default: Date.now,
    index: true,
  },
  resolvedAt: Date,
  expiresAt: Date, // Some alerts expire if not acted upon

  // User interaction
  viewedBy: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  }],
  actionTakenBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  userNotes: String,
  ignoreReason: String,
  ignoredUntil: Date, // If user chooses to ignore for X days

  // AI-generated insights
  insights: [String],

  // Context data (raw data that triggered alert)
  contextData: mongoose.Schema.Types.Mixed,

  // Language
  language: {
    type: String,
    enum: ['es', 'en'],
    default: 'es',
  },

  // AI usage
  aiModel: String,
  tokensUsed: Number,

}, {
  timestamps: true,
});

// Compound indexes
alertSchema.index({ userId: 1, status: 1, createdAt: -1 });
alertSchema.index({ userId: 1, category: 1, status: 1 });
alertSchema.index({ userId: 1, severity: 1, status: 1 });
alertSchema.index({ status: 1, expiresAt: 1 });

/**
 * Get pending alerts for user
 */
alertSchema.statics.getPendingAlerts = async function(userId, limit = 50) {
  return this.find({
    userId,
    status: 'pending',
    $or: [
      { expiresAt: null },
      { expiresAt: { $gt: new Date() } },
    ],
  })
    .sort({ severity: -1, createdAt: -1 }) // Critical first, then newest
    .limit(limit);
};

/**
 * Get alert summary for dashboard
 */
alertSchema.statics.getAlertSummary = async function(userId) {
  const now = new Date();

  const summary = await this.aggregate([
    {
      $match: {
        userId: new mongoose.Types.ObjectId(userId),
        // Only count non-expired alerts
        $or: [
          { expiresAt: null },
          { expiresAt: { $gt: now } },
        ],
      },
    },
    {
      $group: {
        _id: '$status',
        count: { $sum: 1 },
      },
    },
  ]);

  const criticalCount = await this.countDocuments({
    userId,
    severity: 'critical',
    status: 'pending',
    $or: [
      { expiresAt: null },
      { expiresAt: { $gt: now } },
    ],
  });

  const result = {
    pending: 0,
    applied: 0,
    inReview: 0,
    ignored: 0,
    resolved: 0,
    critical: criticalCount,
    total: 0,
  };

  summary.forEach(item => {
    const status = item._id;
    if (status === 'in_review') {
      result.inReview = item.count;
    } else {
      result[status] = item.count;
    }
    result.total += item.count;
  });

  // Get last alert time (from non-expired alerts)
  const lastAlert = await this.findOne({
    userId,
    $or: [
      { expiresAt: null },
      { expiresAt: { $gt: now } },
    ],
  })
    .sort({ createdAt: -1 })
    .select('createdAt');

  result.lastAlertTime = lastAlert ? lastAlert.createdAt : null;

  return result;
};

/**
 * Get alerts by category
 */
alertSchema.statics.getAlertsByCategory = async function(userId) {
  return this.aggregate([
    {
      $match: {
        userId: new mongoose.Types.ObjectId(userId),
        status: { $ne: 'ignored' },
      },
    },
    {
      $group: {
        _id: '$category',
        count: { $sum: 1 },
        criticalCount: {
          $sum: {
            $cond: [{ $eq: ['$severity', 'critical'] }, 1, 0],
          },
        },
        lastAlert: { $max: '$createdAt' },
      },
    },
    {
      $project: {
        _id: 0,
        category: '$_id',
        count: 1,
        criticalCount: 1,
        lastAlert: 1,
      },
    },
    { $sort: { criticalCount: -1, count: -1 } },
  ]);
};

/**
 * Mark alert as viewed by user
 */
alertSchema.methods.markAsViewed = function(userId) {
  if (!this.viewedBy.includes(userId)) {
    this.viewedBy.push(userId);
  }
  return this.save();
};

/**
 * Apply recommended action
 */
alertSchema.methods.applyAction = function(actionId, userId) {
  const action = this.recommendedActions.id(actionId);

  if (!action) {
    throw new Error('Action not found');
  }

  if (action.applied) {
    throw new Error('Action already applied');
  }

  action.applied = true;
  action.appliedAt = new Date();
  action.appliedBy = userId;

  // Update alert status
  this.status = 'applied';
  this.actionTakenBy = userId;

  return this.save();
};

/**
 * Ignore alert
 */
alertSchema.methods.ignore = function(userId, reason = '', ignoreForDays = 0) {
  this.status = 'ignored';
  this.actionTakenBy = userId;
  this.ignoreReason = reason;

  if (ignoreForDays > 0) {
    this.ignoredUntil = new Date(Date.now() + ignoreForDays * 24 * 60 * 60 * 1000);
  }

  return this.save();
};

/**
 * Mark for review
 */
alertSchema.methods.markForReview = function(userId, notes = '') {
  this.status = 'in_review';
  if (notes) {
    this.userNotes = notes;
  }
  if (!this.viewedBy.includes(userId)) {
    this.viewedBy.push(userId);
  }
  return this.save();
};

/**
 * Resolve alert
 */
alertSchema.methods.resolve = function(userId, notes = '') {
  this.status = 'resolved';
  this.resolvedAt = new Date();
  this.actionTakenBy = userId;
  if (notes) {
    this.userNotes = notes;
  }
  return this.save();
};

/**
 * Check if alert has expired
 */
alertSchema.methods.isExpired = function() {
  return this.expiresAt && this.expiresAt < new Date();
};

/**
 * Expire old pending alerts (called by cleanup job)
 */
alertSchema.statics.expireOldAlerts = async function() {
  const result = await this.updateMany(
    {
      status: 'pending',
      expiresAt: { $lt: new Date() },
    },
    {
      $set: {
        status: 'resolved',
        resolvedAt: new Date(),
        userNotes: 'Auto-resolved: Alert expired',
      },
    }
  );

  return result.modifiedCount;
};

const Alert = mongoose.model('Alert', alertSchema);

module.exports = Alert;
